[listen]
api = "0.0.0.0:3302"
publish = "0.0.0.0:3303"

[api]
#disable or not api service
disable = false
#access api token
token = "abc123"

[publish]
#these http headers will be ignored when access to consumer's url
#User-Agent Token RouteKey Host Accept-Encoding  Content-Length Content-Type Connection headers will be ignored by force
IgnoreHeaders = []
#the publisher's real ip will be set in this http header when access to consumer's url
RealIpHeader = "X-Forwarded-For"

[consume]
#access consumer url  fail and then how many time to sleep
FailWait = 50000
DataFile = "message.json"

[rabbitmq]
host = "127.0.0.1"
port = 5672
username = "guest"
password = "guest"
vhost = "/"
#the queue and exchange default prefix
prefix = "wmq."
[log]
#which level log to file,default:["info","error","debug"]
level = ["info","error","debug"]
dir = log


